-- CREATING DATABASE --
DROP DATABASE burger_db;
CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name varchar(255) NOT NULL,
	devoured BOOLEAN DEFAULT false
);
